### ISSUE TITLE
Please 2023.1

### ISSUE THREAD

**Issue by xiaohanlong** [Spectrall368/Generator-1.16.5#1]
Please,2023.1

**Comment by Spectrall368** [comment]
I'm working on it

**Comment by xiaohanlong** [comment]
> I'm working on it

Thanks！！
Will you support some of the new features in 2023.1？Even all of them.（crazy）

**Comment by Spectrall368** [comment]
I don't think so since 1.16.5 doesn't support these new features, I'll see what I can do.

**Comment by xiaohanlong** [comment]
nice

**Comment by Spectrall368** [comment]
Support for MCreator 2023.1 at the moment: 
![image](https://user-images.githubusercontent.com/105946758/233190005-e207ec96-f9f3-42ca-8856-e37f71f2f590.png)

**Comment by Spectrall368** [comment]
I'm doing some debugging and the only thing I need to fix is ​​a bug on the gui that I'll fix soon and not now

**Comment by xiaohanlong** [comment]
>

Amazing
Because of you, 1.16.5 is still the winner!:）

**Comment by Spectrall368** [comment]
The plugin is complete, i just need to fix the bugs on the gui and also on the biomes

**Comment by Spectrall368** [comment]
since i'm not very good in java i have a bit of difficulty so it might take longer than expected :(

**Comment by SecretSeasons2** [comment]
> since i'm not very good in java i have a bit of difficulty so it might take longer than expected :(
Two months later?

**Comment by xiaohanlong** [comment]
> since i'm not very good in java i have a bit of difficulty so it might take longer than expected :(

Two months?I'm sorry I can't help you. I'm just a Mod maker.Do you want to see the Adventure Mod I'm working on?

**Comment by Spectrall368** [comment]
I'll take longer if I don't find the solution to the problem, ok.

**Comment by xiaohanlong** [comment]
> I'll take longer if I don't find the solution to the problem, ok.

1.16.5Forge
![1682053392992](https://user-images.githubusercontent.com/88470726/233545560-90f50462-1a2c-484d-ae71-cfd0f0754e65.png)

![1682053409318](https://user-images.githubusercontent.com/88470726/233545568-55f8deee-1ef9-45f7-bc7d-bfd2e9da96c4.png)

![12785916820534572](https://user-images.githubusercontent.com/88470726/233545571-f497ac1a-0b04-432f-bfd9-823fdb41a5fc.png)

**Comment by Spectrall368** [comment]
Made with Kleiders plugin for MCreator 2022.3 I guess

**Comment by Spectrall368** [comment]
Regarding the biome and the gui I will try to redo them from 0 hoping they will work, taking the biome  and Gui file from MCreator 2022.2 and try to see if it works

**Comment by xiaohanlong** [comment]
> Made with Kleiders plugin for MCreator 2022.3 I guess

Just one of them.I use a lot of plugins.

**Comment by xiaohanlong** [comment]
> 

Amazing！Good Luck to you！

**Comment by Spectrall368** [comment]
Thanks

**Comment by xiaohanlong** [comment]
> Thanks

It feels like you're always here. Are you Chinese, too?

**Comment by Spectrall368** [comment]
No

**Comment by Spectrall368** [comment]
since i can't fix the bugs i will publish the plugin in beta until i find a fix

**Comment by xiaohanlong** [comment]
> 
Maybe this bug can't be fixed?

**Comment by Spectrall368** [comment]
Can they be fixed the problem is that as i said before i'm not expert in java and i don't have that much experience with plugins so a person with more knowledge would know how to fix them

**Comment by xiaohanlong** [comment]
Long time no see, have you made any progress?

**Comment by Spectrall368** [comment]
> Long time no see, have you made any progress?

I had lost hope, then in the previous days I did it again and it works perfectly, I only need to fix 1 little thing about generating the code for the items (which for the moment I don't know how to fix)

**Comment by Spectrall368** [comment]
Done

**Comment by SecretSeasons2** [comment]
I'm glad you released version 1.3. Is there any issue this version has to address? Can I upgrade my large mod?

**Comment by SecretSeasons2** [comment]
I'm glad you released version 1.3. Are there any unresolved issues with this version? Can I upgrade my large module?

**Comment by xiaohanlong** [comment]
I'm glad you released version 1.3. Are there any unresolved issues with this version? Can I upgrade my large mod?

**Comment by Spectrall368** [comment]
> I'm glad you released version 1.3. Are there any unresolved issues with this version? Can I upgrade my large mod?

The version is stable, there should be no errors, I also did various tests with my workspaces
