### ISSUE TITLE
The method getPos|X/Y/Z]() is undefined for the type BlockPos

### ISSUE THREAD

**Issue by DarkShoro** [Spectrall368/Generator-1.16.5#8]
Using ver 1.3.1

Calling a procedure when a block is destroyed using an item result in the compilation error "The method getPos|X/Y/Z]() is undefined for the type BlockPos"

SOLUTION: use "get|X/Y/Z]()" instead of "getPos|X/Y/Z]()"

**Comment by Spectrall368** [comment]
Fixed! The fix will arrive in the next update
