### ISSUE TITLE
easy fix

### ISSUE THREAD

**Issue by Dannimo7** [Spectrall368/Generator-1.16.5#9]
hi! this issue was just to comment u about the zip file when its downloaded the last update for the 2023.1- 1.4, when its downloaded here, the .zip causes a folder to be generated when downloaded and within that folder all the files are generated, so when putting it in the plugins it generates an error, removing the folder solves it, it is an observation in case you like to have everything in order :D

**Comment by Spectrall368** [comment]
When you download the source code on github that folder is created (that's why I release the download on MCreator or on the Releases section on github) and in any case the release will be out soon
